services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      # VPN here
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      # custom.conf == Airvpn.ovpn
      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf
      - FIREWALL_VPN_INPUT_PORTS=59024
      #- LOG_LEVEL=debug
    ports:
      - 8080:8080 # webui
      - 59024:59024/tcp
      - 59024:59024/udp
    restart: always
    volumes:
      - ./gluetun:/gluetun
    env_file:
      - .env
    devices:
      - /dev/net/tun:/dev/net/tun

  qbittorrent-nox:
    container_name: qbittorrent
    environment:
      - PGID=1000
      - PUID=1000
      - QBT_LEGAL_NOTICE=confirm
      - QBT_VERSION=latest
      - QBT_WEBUI_PORT=8080
      - TZ=America/New_York
    image: qbittorrentofficial/qbittorrent-nox:latest
    network_mode: "service:gluetun" # CRUCIAL
    read_only: true
    depends_on:
      gluetun:
        condition: service_healthy
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - ./config:/config
      - /shared:/downloads
    restart: always
